---
- name: Deploy Prometheus, Node Exporter, ElasticSearch, and FluentBit
  hosts: localhost
  become: yes  # Use sudo for privilege escalation if needed

  tasks:
    - name: Turn off d SELINUX
      command: setenforce 0
#    - name: Turn off firewalld
#      command: 
  
  roles:
    - prereq
    - prometheus
    - node_exporter
    - elasticsearch_kibana
#    - fluentbit
  handlers:
    - name: Reload Prometheus
      systemd:
        name: prometheus
        state: reloaded
