---
- name: Add Prometheus Repository
  yum_repository:
    name: Prometheus
    description: Prometheus Repository
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
    gpgcheck: no
    enabled: yes

- name: Install fluentbit repo
  command: rpm -ivh https://packages.fluentbit.io/centos/8/fluentbit_repo.x86_64.rpm
  async: 300
  poll: 0
  args:
    chdir: /tmp  # You can specify a different directory if needed
  become: yes

